import { useEffect, useMemo, useRef, useState } from "react";
import type { Rescue } from "../api.js";
import { Badge } from "./ui/badge.js";
import { Button } from "./ui/button.js";
import { Card, CardContent, CardHeader, CardTitle } from "./ui/card.js";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "./ui/dialog.js";

const PAGE_SIZE = 30;
export function RescueHistory({ rescues, error = false, onRetry }: { rescues: Rescue[]; error?: boolean; onRetry?: () => void }) { const [open, setOpen] = useState(false); return <Card><CardHeader><p className="font-mono text-xs uppercase tracking-[0.2em] text-primary">Audit trail</p><CardTitle>Rescue history</CardTitle></CardHeader><CardContent>{error ? <div className="flex items-center justify-between gap-4 text-sm text-risk"><span>Rescue history is temporarily unavailable.</span><button type="button" className="underline" onClick={onRetry}>Retry</button></div> : rescues.length === 0 ? <div className="border border-dashed border-border p-6 text-sm text-muted-foreground">No rescues yet. Completed transactions will appear here.</div> : <><div className="space-y-2">{rescues.slice(0, 8).map((rescue) => <RescueRow key={rescue.txHash} r={rescue} />)}</div>{rescues.length > 8 && <Button variant="outline" size="sm" className="mt-4 w-full" onClick={() => setOpen(true)}>View all {rescues.length} rescues</Button>}</>}</CardContent><HistoryModal open={open} rescues={rescues} onClose={() => setOpen(false)} /></Card>; }
function RescueRow({ r }: { r: Rescue }) { return <div className="flex flex-wrap items-center gap-3 border border-border bg-background p-3"><Badge variant={r.type === "repay" ? "default" : "success"}>{r.type === "repay" ? "Repaid" : "Supplied"}</Badge><span className="font-medium"><span className="font-mono">{fmt(r.amountHuman)}</span> {r.asset}</span><span className="font-mono text-xs text-muted-foreground">block {r.block.toLocaleString()}</span><a href={r.link} target="_blank" rel="noreferrer" className="ml-auto font-mono text-xs text-primary hover:underline">{short(r.txHash)} ↗</a></div>; }
function HistoryModal({ open, rescues, onClose }: { open: boolean; rescues: Rescue[]; onClose: () => void }) { const [count, setCount] = useState(PAGE_SIZE); const sentinelRef = useRef<HTMLDivElement | null>(null); const listRef = useRef<HTMLDivElement | null>(null); const visible = useMemo(() => rescues.slice(0, count), [rescues, count]); const hasMore = count < rescues.length; useEffect(() => { const el = sentinelRef.current; if (!el || !hasMore || typeof IntersectionObserver === "undefined") return; const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) setCount((value) => Math.min(value + PAGE_SIZE, rescues.length)); }, { root: listRef.current, rootMargin: "120px" }); observer.observe(el); return () => observer.disconnect(); }, [hasMore, rescues.length]); return <Dialog open={open} onOpenChange={onClose}><DialogContent className="flex max-h-[80vh] max-w-2xl flex-col"><DialogHeader><DialogTitle>Rescue history</DialogTitle><DialogDescription>{rescues.length} rescues, newest first</DialogDescription></DialogHeader><div ref={listRef} className="mt-6 space-y-2 overflow-y-auto">{visible.map((rescue) => <RescueRow key={rescue.txHash} r={rescue} />)}<div ref={sentinelRef} className="h-2" />{hasMore && <p className="py-2 text-center text-xs text-muted-foreground">Scrolling loads more…</p>}</div><Button variant="outline" size="sm" className="mt-6 self-end" onClick={onClose}>Close</Button></DialogContent></Dialog>; }
function fmt(value: number) { return value.toLocaleString(undefined, { maximumFractionDigits: 6 }); }
function short(hash: string) { return `${hash.slice(0, 10)}…${hash.slice(-6)}`; }
